import { expect, test } from "@playwright/test";

test("custom skill persists, prompt application can be undone, mobile fits", async ({ page }) => {
  await page.goto("/skill");
  const login = page.getByRole("dialog", { name: "登录", exact: true });
  await login.getByPlaceholder("请输入手机号").fill("13800138000");
  await login.getByPlaceholder("6 位验证码").fill("123456");
  await login.getByRole("checkbox").check();
  await login.getByRole("button", { name: "登录", exact: true }).click();
  await expect(page).toHaveURL(/\/skill$/);
  await page.getByRole("button", { name: "提示词与自定义技能" }).click();
  await page.getByRole("button", { name: "自定义技能", exact: true }).click();
  await page.getByLabel("技能名称", { exact: true }).fill("测试写实规则");
  await page.getByLabel("技能规则", { exact: true }).fill("保留自然光，不改变人物服装。");
  await page.getByRole("button", { name: "保存技能" }).click();
  await expect(page.getByText("测试写实规则", { exact: true })).toBeVisible();
  await page.reload();
  await page.getByRole("button", { name: "提示词与自定义技能" }).click();
  await expect(page.getByText("测试写实规则", { exact: true })).toBeVisible();
  await page.getByLabel("分镜内容或视频提示词", { exact: true }).fill("林安走进院子。");
  await page.getByRole("checkbox", { name: /测试写实规则/ }).check();
  await page.getByRole("button", { name: "生成规则预览" }).click();
  await expect(page.getByLabel("提示词预览（可编辑）")).toHaveValue(/保留自然光/);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: "/tmp/bollo-skills-mobile.png" });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto("/project/2?tab=prompts");
  await expect(page.getByRole("region", { name: "提示词工作台" })).toBeVisible();
  await page.getByRole("button", { name: "生成规则预览" }).click();
  await page.getByRole("button", { name: "应用到当前镜头" }).click();
  await expect(page.getByText("已应用到当前镜头", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "撤销应用" }).click();
  await expect(page.getByText("已撤销本次应用", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "去瑕疵", exact: true }).click();
  await page.getByLabel("分镜内容或视频提示词", { exact: true }).fill("推近同时拉远");
  await expect(page.getByText("同时出现推近与拉远，请确认是否为先后动作。")).toBeVisible();
  await page.screenshot({ path: "/tmp/bollo-prompts-desktop.png" });
});
