import { expect, test } from "@playwright/test";

test("script editing, project configuration, preview and restore", async ({ page }) => {
  await page.goto("/project/2?tab=script");
  const login = page.getByRole("dialog", { name: "登录", exact: true });
  await login.getByPlaceholder("请输入手机号").fill("13800138000");
  await login.getByPlaceholder("6 位验证码").fill("123456");
  await login.getByRole("checkbox").check();
  await login.getByRole("button", { name: "登录", exact: true }).click();
  await expect(page.getByLabel("剧本正文", { exact: true })).toBeVisible();
  await page.getByLabel("剧本正文", { exact: true }).fill("林安走进院子。林安发现门已经打开。");
  await page.getByRole("button", { name: "保存版本", exact: true }).click();
  await page.getByRole("button", { name: "剧本偏好", exact: true }).click();
  const modal = page.getByRole("dialog", { name: "剧本创编偏好" });
  await modal.getByLabel("助手名称", { exact: true }).fill("项目专属编剧");
  await modal.getByRole("button", { name: "添加自定义技能" }).click();
  await modal.getByLabel("技能 4 名称").fill("人物检查");
  await modal.getByLabel("技能 4 规则").fill("不增加新角色");
  await modal.getByRole("button", { name: "测试当前配置" }).click();
  await expect(modal.getByLabel("配置测试结果")).toHaveValue(/不增加新角色/);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: "/tmp/bollo-script-settings-mobile.png" });
  await modal.getByRole("button", { name: "保存项目配置" }).click();
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.reload();
  await expect(page.getByLabel("剧本正文", { exact: true })).toHaveValue("林安走进院子。林安发现门已经打开。");
  await page.getByLabel("修改方式").selectOption("replace");
  await page.getByLabel("需要替换的原文").fill("林安");
  await page.getByLabel("替换为", { exact: true }).fill("沈清");
  await page.getByRole("button", { name: "预览替换" }).click();
  await expect(page.getByLabel("剧本正文", { exact: true })).toHaveValue(/林安/);
  await expect(page.getByLabel("修改稿预览（完整剧本）")).toHaveValue("沈清走进院子。沈清发现门已经打开。");
  await page.getByRole("button", { name: "确认应用并保存" }).click();
  await expect(page.getByLabel("剧本正文", { exact: true })).toHaveValue(/沈清/);
  await page.getByRole("button", { name: "历史记录", exact: true }).click();
  await page.getByRole("button", { name: /v2 · 手动编辑/ }).click();
  page.once("dialog", (dialog) => dialog.accept());
  await page.getByRole("button", { name: "恢复为新版本" }).click();
  await expect(page.getByLabel("剧本正文", { exact: true })).toHaveValue(/林安/);
  await page.reload();
  await expect(page.getByLabel("剧本正文", { exact: true })).toHaveValue(/林安/);
  await page.getByRole("link", { name: "下一步：分镜提示词" }).click();
  await expect(page).toHaveURL(/tab=prompts/);
  await expect(page.getByRole("region", { name: "提示词工作台" })).toBeVisible();
  await page.getByRole("button", { name: "剧本", exact: true }).click();
  await expect(page).toHaveURL(/tab=script/);
  await page.reload();
  await expect(page.getByLabel("剧本正文", { exact: true })).toHaveValue(/林安/);
  await page.goBack();
  await expect(page.getByRole("region", { name: "提示词工作台" })).toBeVisible();
  await page.goForward();
  await page.getByRole("button", { name: "剧本偏好", exact: true }).click();
  await modal.getByLabel("助手名称", { exact: true }).fill("未保存配置");
  page.once("dialog", (dialog) => dialog.dismiss());
  await modal.getByRole("button", { name: "取消", exact: true }).click();
  await expect(modal.getByLabel("助手名称", { exact: true })).toHaveValue("未保存配置");
  page.once("dialog", (dialog) => dialog.accept());
  await modal.getByRole("button", { name: "取消", exact: true }).click();
  await page.screenshot({ path: "/tmp/bollo-script-studio.png" });
  await page.goto("/project/3?tab=script");
  await page.getByRole("button", { name: "剧本偏好", exact: true }).click();
  await expect(page.getByLabel("助手名称", { exact: true })).toHaveValue("剧本创编助手");
});
